export const data = [
  {
    id: 1,
    firstName: "Suresh",
    lastName: "Galla",
    email: "suresh@gmail.com",
    contact: 8919285592,
    role: "FrontEnd Developer",
  },
  {
    id: 2,
    firstName: "Ashok",
    lastName: "Pasala",
    email: "ashok@gmail.com",
    contact: 6301524335,
    role: "Trader",
  },
  {
    id: 3,
    firstName: "Sai",
    lastName: "Pasala",
    email: "sai@gmail.com",
    contact: 6302789342,
    role: "Designer",
  },
  {
    id: 4,
    firstName: "Chiru",
    lastName: "Yeduvaka",
    email: "chiru@gmail.com",
    contact: 7083898899,
    role: "Marketing Manger",
  },
  {
    id: 5,
    firstName: "Venky",
    lastName: "Reddy",
    email: "venky@gmail.com",
    contact: 8978282828,
    role: "Backend Developer",
  },
];
